### ISSUE TITLE
GitHub replaces the NotFound page of Blazor with its own 404 page.

### ISSUE THREAD

**Issue by ndsvw** [Swimburger/BlazorGitHubPagesDemo#1]
Your article on [https://swimburger.net/blog/dotnet/how-to-deploy-aspnet-blazor-webassembly-to-github-pages](url) helped me a lot.

But there is one thing worth to mention IMO: If a page does not exist (e.g. /not-existing-page), GitHub will show its own 404 page.
You could overcome this and let the Blazor router display the Blazor-NotFound-page by replacing ...

` run:`
`      sed -i 's/<base href="\/" \/>/<base href="\/BlazorGitHubPagesDemo\/" \/>/g' release/wwwroot/index.html`
... with this:
` run: |`
`      sed -i 's/<base href="\/" \/>/<base href="\/BlazorGitHubPagesDemo\/" \/>/g' release/wwwroot/index.html`
`      cp release/wwwroot/index.html release/wwwroot/404.html`

**Comment by Swimburger** [comment]
Thank you for the suggestion, I'll play around with this!

**Comment by Swimburger** [comment]
I updated this repository and the tutorial with your suggestion. Thank you!
