### ISSUE TITLE
Net 5

### ISSUE THREAD

**Issue by srezasm** [Swimburger/BlazorGitHubPagesDemo#2]
Due to major updates of the Blazor in Net 5 please update this repository and associated article

**Comment by Swimburger** [comment]
Thank you for reaching out. The article should be compatible with .NET 5. Let me know if there's something missing.

You do have to update the `dotnet-version` property in the GitHub Actions workflow.

The video version uses .NET 5: https://www.youtube.com/watch?v=nNxII6jvPvQ
Also this workflow uses .NET 5: https://github.com/Swimburger/BlazorGitHubPagesDemo/blob/pwa/.github/workflows/pwa.yml

Check the version you're using with the command `dotnet --info`.

Does that help?

**Comment by srezasm** [comment]
Yes, thanks

**Comment by srezasm** [comment]
Yes, thanks
