### ISSUE TITLE
Issue with refreshing apps hosted on github pages

### ISSUE THREAD

**Issue by dharmatech** [Swimburger/BlazorGitHubPagesDemo#3]
Hello,

Great tutorial, thank you!

Just wanted to point out that I ran into this issue:

https://stackoverflow.com/questions/73148378/blazor-wasm-app-on-github-pages-loads-however-refresh-results-in-404

A workaround is mentioned there.

**Comment by Swimburger** [comment]
My blog post and video suggest to copy the index.html to 404.html so it'll be used instead of GitHub's default 404 page.
This should fix the issue mentioned. See "copy index.html to 404.html" in https://github.com/Swimburger/BlazorGitHubPagesDemo/blob/master/.github/workflows/main.yml

**Comment by dharmatech** [comment]
Ah, OK. Thank you.

That section sounded like it was for folks who wanted to change the github-branded 404 page to their own, so it seemed optional.

Consider adding a note in there saying that it's actually recommended since without it folks may run into the refresh issue.
